plugins/action/asa.py, plugins/cliconf/asa.py, plugins/modules/asa_acl.py, plugins/modules/asa_config.py, plugins/modules/asa_og.py, plugins/terminal/asa.py, tox.ini
This helps make our code a little better.
=> Fix F401,F841 flake8 errors

plugins/cliconf/asa.py, plugins/module_utils/network/asa/argspec/facts/facts.py, plugins/module_utils/network/asa/asa.py, plugins/module_utils/network/asa/facts/facts.py, plugins/module_utils/network/asa/facts/legacy/base.py, plugins/modules/asa_facts.py, tests/integration/targets/asa_facts/defaults/main.yaml, tests/integration/targets/asa_facts/tasks/cli.yaml, tests/integration/targets/asa_facts/tasks/main.yaml, tests/integration/targets/asa_facts/tests/cli/all_facts.yaml, tests/integration/targets/asa_facts/tests/cli/default_facts.yaml, tests/integration/targets/asa_facts/tests/cli/invalid_subset.yaml, tests/integration/targets/asa_facts/tests/cli/not_hardware.yaml, tests/unit/modules/network/asa/fixtures/asa_facts_dir, tests/unit/modules/network/asa/fixtures/asa_facts_show_memory, tests/unit/modules/network/asa/fixtures/asa_facts_show_version, tests/unit/modules/network/asa/test_asa_facts.py
Implementation of Cisco ASA facts module, which will enable fact generation from Cisco ASA.
asa_facts
asa_facts play:
```
---
- hosts: asa
connection: network_cli
become: yes
tasks:
- name: Gather legacy and resource facts
asa_facts:
gather_subset: all
```
Facts Out:
```
"ansible_facts": {
"ansible_net_api": "cliconf",
"ansible_net_asatype": "ASA",
"ansible_net_device_mgr_version": "7.10(1)",
"ansible_net_filesystems": [
"disk0:"
],
"ansible_net_filesystems_info": {
"disk0:": {
"spacefree_kb": 8348976.0,
"spacetotal_kb": 8370192.0
}
},
"ansible_net_firepower_version": "2.4(1.227)",
"ansible_net_gather_network_resources": [],
"ansible_net_gather_subset": [
"hardware",
"default"
],
"ansible_net_hostname": "ciscoasa",
"ansible_net_image": …
```
=> Implementation of Cisco ASA facts module

plugins/module_utils/network/asa/config/acls/acls.py, plugins/modules/asa_acls.py
PR to resolve Cisco ASA rename traceback issue, resolves issue https://github.com/ansible-collections/asa/issues/13
asa_acls
```paste below
```
=> PR to resolve Cisco ASA rename traceback issue

plugins/module_utils/network/asa/config/acls/acls.py, plugins/module_utils/network/asa/facts/acls/acls.py, tests/integration/targets/asa_acls/tests/cli/merged.yaml, tests/integration/targets/asa_acls/vars/main.yaml
To fix the failure reported in https://github.com/ansible-collections/asa/issues/15 which fixes Cisco ASA ACLs module failure when trying to configure ICMP/ICMP6
asa_acls
```paste below
```
=> Fixes Cisco ASA ACLs module failure when trying to configure ICMP/ICMP6

README.md, galaxy.yml
=> Rename to ansible-collections/cisco.asa

test-requirements.txt, tests/integration/network-integration.cfg
=> Add missing ansible.cfg for integration testing

test-requirements.txt
Signed-off-by: GomathiselviS <gomathiselvi@gmail.com>
Add test requirement coverage==4.5.4
=> [cisco.asa] Add test requirement for coverage

plugins/module_utils/network/asa/config/acls/acls.py, tests/integration/targets/asa_acls/tests/cli/deleted.yaml, tests/integration/targets/asa_acls/vars/main.yaml
Update delete operation to delete only by ACLs and not by ACEs
asa_acls
```paste below
```
=> Update delete operation to delete only by ACLs and not by ACEs

plugins/modules/asa_acl.py, plugins/modules/asa_acls.py, plugins/modules/asa_command.py, plugins/modules/asa_config.py, plugins/modules/asa_facts.py, plugins/modules/asa_og.py, plugins/modules/asa_ogs.py, tests/integration/targets/asa_ogs/tests/cli/overridden.yaml, tests/integration/targets/asa_ogs/tests/cli/replaced.yaml
PR to make Cisco ASA collection release ready 
asa_*
```paste below
```
=> PR to make Cisco ASA collection release ready 

plugins/module_utils/network/asa/argspec/acls/acls.py, plugins/module_utils/network/asa/facts/acls/acls.py, tests/integration/targets/asa_acls/tests/cli/merged.yaml, tests/integration/targets/asa_acls/vars/main.yaml
To fix ASA ACLs source/destination host argspec issue, fixes issue raised in #34 
asa_acls
```paste below
```
=> To fix ASA ACLs source/destination host argspec issue

plugins/module_utils/network/asa/argspec/acls/acls.py, plugins/module_utils/network/asa/config/acls/acls.py, plugins/module_utils/network/asa/facts/acls/acls.py, plugins/modules/asa_acls.py, tests/integration/targets/asa_acls/tests/cli/_populate_network_og.yaml, tests/integration/targets/asa_acls/tests/cli/_remove_og_config.yaml, tests/integration/targets/asa_acls/tests/cli/merged.yaml, tests/integration/targets/asa_acls/tests/cli/overridden.yaml, tests/integration/targets/asa_acls/tests/cli/replaced.yaml, tests/integration/targets/asa_acls/tests/cli/rtt.yaml, tests/integration/targets/asa_acls/vars/main.yaml, tests/unit/modules/network/asa/test_asa_acls.py
Added implementation for interface and network object group that can now be added from source/destination side. Fixes #24 
asa_acls
```paste below
```
=> Added implementation for interface and network object group that can now be added from source/destination side

README.md, docs/cisco.asa.asa.rst, docs/cisco.asa.asa_acl.rst, docs/cisco.asa.asa_acls.rst, docs/cisco.asa.asa_command.rst, docs/cisco.asa.asa_config.rst, docs/cisco.asa.asa_facts.rst, docs/cisco.asa.asa_og.rst, docs/cisco.asa.asa_ogs.rst, plugins/cliconf/asa.py
Added *.rst files for all of ASA modules for collection 1.0.0
asa_*
```paste below
```
=> Added *.rst files for all of ASA modules for collection 1.0.0

README.md
Signed-off-by: Sumit Jaiswal <sjaiswal@redhat.com>
To Update and fix broken readme zuul link
README.md
```paste below
```
=> To Update and fix broken readme zuul link

README.md
=> add link to contributor guide etc

plugins/module_utils/network/asa/argspec/acls/acls.py, plugins/module_utils/network/asa/config/acls/acls.py, plugins/module_utils/network/asa/facts/acls/acls.py, plugins/modules/asa_acls.py, tests/unit/compat/mock.py, tests/unit/modules/network/asa/fixtures/asa_acls_config.cfg, tests/unit/modules/network/asa/test_asa_acls.py
To fix ASA source/destination host and remark issue, where remark was not getting published to config and with host idempotency was broken in absence of line number in the want config.
asa_acls.py
```paste below
```
=> To fix ASA source/destination host and remark issue

README.md, docs/cisco.asa.asa_acl_module.rst, docs/cisco.asa.asa_acls_module.rst, docs/cisco.asa.asa_cliconf.rst, docs/cisco.asa.asa_command_module.rst, docs/cisco.asa.asa_config_module.rst, docs/cisco.asa.asa_facts_module.rst, docs/cisco.asa.asa_og_module.rst, docs/cisco.asa.asa_ogs_module.rst, meta/runtime.yml, plugins/module_utils/network/asa/argspec/acls/acls.py, plugins/module_utils/network/asa/argspec/ogs/ogs.py, plugins/module_utils/network/asa/facts/facts.py, plugins/module_utils/network/asa/facts/ogs/ogs.py, plugins/module_utils/network/asa/utils/utils.py, plugins/modules/asa_acl.py, plugins/modules/asa_config.py, plugins/modules/asa_ogs.py, tests/unit/compat/mock.py, tests/unit/modules/network/asa/test_asa_acls.py, tests/unit/modules/network/asa/test_asa_ogs.py
Update ASA Readme and runtime.yml
```paste below
```
=> Update ASA Readme and runtime.yml

.gitignore, plugins/doc_fragments/asa.py, plugins/module_utils/network/asa/asa.py, tests/sanity/ignore-2.10.txt, tests/sanity/ignore-2.9.txt, tests/unit/mock/path.py, tests/unit/mock/yaml_helper.py, tests/unit/modules/conftest.py, tests/unit/modules/utils.py
- Test Pull Request
```paste below
```
=> Clean up boilerplate ignores

.yamllint, changelogs/CHANGELOG.rst, changelogs/changelog.yaml, changelogs/config.yaml, changelogs/fragments/48-add-change-log-1.0.0.yaml
*  Add changelog file for 1.0.0 release genereated
using https://github.com/ansible-community/antsibull-changelog
```paste below
```
=> Add changelog files

README.md
=> Update references of master to main

changelogs/fragments/1.1.0_update_docs.yaml, docs/cisco.asa.asa_acl_module.rst, docs/cisco.asa.asa_acls_module.rst, docs/cisco.asa.asa_cliconf.rst, docs/cisco.asa.asa_command_module.rst, docs/cisco.asa.asa_config_module.rst, docs/cisco.asa.asa_facts_module.rst, docs/cisco.asa.asa_og_module.rst, docs/cisco.asa.asa_ogs_module.rst
To Update ASA 1.1.0 docs having sanity fixes
asa
```paste below
```
=> To Update ASA 1.1.0 docs having sanity fixes

changelogs/CHANGELOG.rst, changelogs/changelog.yaml, changelogs/fragments/1.1.0_update_docs.yaml, changelogs/fragments/48-add-change-log-1.0.0.yaml, changelogs/fragments/fix_config_module_src_backup.yaml, changelogs/fragments/remove_asa_ignore.yaml
Update ASA changelog
asa
```paste below
```
=> Update ASA changelog

README.md, changelogs/CHANGELOG.rst, changelogs/changelog.yaml, docs/cisco.asa.asa_acl_module.rst, docs/cisco.asa.asa_acls_module.rst, docs/cisco.asa.asa_command_module.rst, docs/cisco.asa.asa_config_module.rst, docs/cisco.asa.asa_facts_module.rst, docs/cisco.asa.asa_og_module.rst, docs/cisco.asa.asa_ogs_module.rst, galaxy.yml
1.0.3 collection release
cisco.asa
```paste below
```
=> 1.0.3 collection release

changelogs/fragments/69_resolves_acl_failure.yaml, plugins/module_utils/network/asa/config/acls/acls.py, plugins/module_utils/network/asa/facts/acls/acls.py
To fix acl issue where in case of source and destination when set to hosts acl cmd fired was unexpected
asa_acls
```paste below
```
=> Unexpected set of CMDs fired when source and destination were both set to hosts acl

requirements.txt
Signed-off-by: GomathiselviS <gomathiselvi@gmail.com>
```paste below
```
=> Dropped ansible from requirements.txt

changelogs/fragments/56_acl_any4_ay6_feature_update_use_rm_approach.yaml, plugins/module_utils/network/asa/argspec/acls/acls.py, plugins/module_utils/network/asa/config/acls/acls.py, plugins/module_utils/network/asa/facts/acls/acls.py, plugins/module_utils/network/asa/rm_templates/acls.py, plugins/modules/asa_acls.py, tests/integration/targets/asa_acls/tests/cli/_populate_config.yaml, tests/integration/targets/asa_acls/tests/cli/deleted.yaml, tests/integration/targets/asa_acls/tests/cli/gathered.yaml, tests/integration/targets/asa_acls/tests/cli/merged.yaml, tests/integration/targets/asa_acls/tests/cli/overridden.yaml, tests/integration/targets/asa_acls/tests/cli/parsed.yaml, tests/integration/targets/asa_acls/tests/cli/rendered.yaml, tests/integration/targets/asa_acls/tests/cli/replaced.yaml, tests/integration/targets/asa_acls/tests/cli/rtt.yaml, tests/integration/targets/asa_acls/vars/main.yaml, tests/unit/modules/network/asa/fixtures/asa_acls_config.cfg, tests/unit/modules/network/asa/test_asa_acls.py
Depends-On: https://github.com/ansible-collections/cisco.asa/pull/80
To add asa feature of supporting any4/any6 for asa_acls source and destination and update to use newer RM approach. Fixes #56 
ios_acls
```paste below
```
=> To add asa feature of supporting any4/any6 for asa_acls source and destination and update to use newer RM approach

changelogs/CHANGELOG.rst, changelogs/changelog.yaml, docs/cisco.asa.asa_acl_module.rst, docs/cisco.asa.asa_acls_module.rst, docs/cisco.asa.asa_command_module.rst, docs/cisco.asa.asa_config_module.rst, docs/cisco.asa.asa_facts_module.rst, docs/cisco.asa.asa_og_module.rst, docs/cisco.asa.asa_ogs_module.rst
ASA collection prep for v1.0.4 tagging
asa
```paste below
```
=> ASA collection prep for v1.0.4 tagging

changelogs/fragments/unittest_fix_for_resource_module_base.yaml, tests/unit/modules/network/asa/test_asa_acls.py, tests/unit/modules/network/asa/test_asa_ogs.py
Fix Unit test cases for new resource_module_base class
as
```paste below
```
=> Fix unit test for resource_module_base

changelogs/fragments/82_acl_replace_not_working_as_expected.yaml, plugins/module_utils/network/asa/config/acls/acls.py, tests/unit/modules/network/asa/fixtures/asa_acls_config.cfg, tests/unit/modules/network/asa/test_asa_acls.py
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/795
To fix ASA acls module where replace wasn’t working as expected. Fixes #82 
asa_acls
```paste below
```
=> To fix ASA acls module where replace wasn’t working as expected

README.md, changelogs/CHANGELOG.rst, changelogs/changelog.yaml, docs/cisco.asa.asa_cliconf.rst, docs/cisco.asa.asa_config_module.rst
Depends-On: ansible/ansible-zuul-jobs#795
Prep for Cisco ASA 2.0.0 release
asa
```paste below
```
=> Prep for Cisco ASA 2.0.0 release

changelogs/fragments/94-remove_tests_sanity_requirements.yml, tests/sanity/requirements.txt
https://github.com/ansible-collections/overview/issues/43
=> Remove tests/sanity/requirements.txt

changelogs/fragments/102-add_ingore_txt.yml, tests/sanity/ignore-2.12.txt
Please, after merge, add 2.11 to the test matrix (I didn't find it)
https://github.com/ansible-collections/overview/issues/45#issuecomment-813821100
=> Add ignore-2.12.txt

CHANGELOG.rst, changelogs/changelog.yaml, docs/cisco.asa.asa_acl_module.rst, docs/cisco.asa.asa_config_module.rst, docs/cisco.asa.asa_ogs_module.rst
Cisco ASA collection prep for v2.0.1 tagging 
asa
```paste below
```
=> Cisco ASA collection prep for v2.0.1 tagging 

changelogs/fragments/black.yaml, plugins/module_utils/network/asa/argspec/acls/acls.py, plugins/module_utils/network/asa/argspec/facts/facts.py, plugins/module_utils/network/asa/argspec/ogs/ogs.py, plugins/module_utils/network/asa/config/acls/acls.py, plugins/module_utils/network/asa/config/ogs/ogs.py, plugins/module_utils/network/asa/facts/acls/acls.py, plugins/module_utils/network/asa/facts/facts.py, plugins/module_utils/network/asa/facts/ogs/ogs.py, plugins/module_utils/network/asa/utils/utils.py, plugins/modules/asa_config.py, test-requirements.txt
Uncap and reformat black to the latest version.
Depends-On: https://github.com/ansible/network-ee/pull/62
=> Uncap black requirement

changelogs/fragments/107_asa_ogs_group_object_implementation.yaml, plugins/module_utils/network/asa/argspec/ogs/ogs.py, plugins/module_utils/network/asa/config/ogs/ogs.py, plugins/module_utils/network/asa/facts/ogs/ogs.py, plugins/module_utils/network/asa/rm_templates/ogs.py, plugins/modules/asa_ogs.py, requirements.txt, tests/unit/modules/network/asa/fixtures/asa_ogs_config.cfg, tests/unit/modules/network/asa/test_asa_ogs.py
Depends-on: https://github.com/ansible/ansible-zuul-jobs/pull/927
To implement asa_ogs group-object parameter which was missing from the module. Fix #107 
asa_ogs
```paste below
```
=> To implement asa_ogs group-object parameter which was missing from the module 

CHANGELOG.rst, changelogs/changelog.yaml, changelogs/fragments/102-add_ingore_txt.yml, changelogs/fragments/105_asa_acls_where_host_ipv6_wasn't_rendered_as_expected.yaml, changelogs/fragments/107_asa_ogs_group_object_implementation.yaml, changelogs/fragments/44_added_save_when_feature.yaml, changelogs/fragments/56_acl_any4_ay6_feature_update_use_rm_approach.yaml, changelogs/fragments/69_resolves_acl_failure.yaml, changelogs/fragments/76_asa_og_state_delete_not_working_as_expected.yaml, changelogs/fragments/82_acl_replace_not_working_as_expected.yaml, changelogs/fragments/94-remove_tests_sanity_requirements.yml, changelogs/fragments/99_asa_ogs_network_object_object_fix.yaml, changelogs/fragments/black.yaml, changelogs/fragments/changelog_doc_path_update.yaml, changelogs/fragments/fix_26_ee_sanity_issues.yaml, changelogs/fragments/galaxy-version.yaml, changelogs/fragments/single_user_mode.yaml, changelogs/fragments/unittest_fix_for_resource_module_base.yaml, docs/cisco.asa.asa_ogs_module.rst
Prepare for Cisco ASA 2.0.2 release
asa
```paste below
```
=> Prepare for Cisco ASA 2.0.2 release

README.md, changelogs/fragments/readme_freenode_to_liberachat.yml
https://github.com/ansible-community/community-topics/issues/19
README.md
=> Update README: freenode -> libera.chat

changelogs/fragments/120_fix_asa_acls_port_range_implementation.yaml, plugins/module_utils/network/asa/rm_templates/acls.py, tests/unit/modules/network/asa/fixtures/asa_acls_config.cfg, tests/unit/modules/network/asa/test_asa_acls.py
To fix asa_acls port range bug, where range implementation was not done as expected and destination host template parsing. Fixes #120, #121, #122, #127
asa_acls
```paste below
```
=> To fix asa_acls port range bug and destination host template parsing

CHANGELOG.rst, changelogs/changelog.yaml, changelogs/fragments/116_ogs_protocol_object_fix.yaml, changelogs/fragments/120_fix_asa_acls_port_range_implementation.yaml, changelogs/fragments/124_asa_ogs_empty_object_traceback_failure.yaml, changelogs/fragments/128_fix_asa_ogs_networkobject_host_with_ipv6.yaml, changelogs/fragments/129_sanity_test_cleanup_for_pylint.yml, changelogs/fragments/132_fix_parameter_documentation.yml, changelogs/fragments/71_fix_NoneType_in_service_group.yaml, changelogs/fragments/97_implement_replace_block_asa_acl.yaml, changelogs/fragments/readme_freenode_to_liberachat.yml, docs/cisco.asa.asa_acl_module.rst, docs/cisco.asa.asa_command_module.rst, docs/cisco.asa.asa_config_module.rst, docs/cisco.asa.asa_facts_module.rst, docs/cisco.asa.asa_ogs_module.rst
PR to prep Cisco asa for 2.0.3 release
asa
```paste below
```
=> PR to prep Cisco asa for 2.0.3 release

.pre-commit-config.yaml, docs/cisco.asa.asa_acl_module.rst, docs/cisco.asa.asa_command_module.rst, docs/cisco.asa.asa_facts_module.rst, docs/cisco.asa.asa_og_module.rst
Committed via https://github.com/asottile/all-repos
=> Updating collection_prep pre-commit hook to 0.9.4

bindep.txt, changelogs/fragments/fix_for_the_ogs_bug_asa_152.yaml, plugins/cliconf/asa.py, plugins/module_utils/network/asa/argspec/ogs/ogs.py, plugins/module_utils/network/asa/facts/ogs/ogs.py, plugins/module_utils/network/asa/rm_templates/ogs.py, plugins/modules/asa_facts.py, plugins/modules/asa_ogs.py, plugins/terminal/asa.py, test-requirements.txt, tests/integration/targets/asa_acls/tasks/cli.yaml, tests/sanity/ignore-2.14.txt, tests/unit/modules/network/asa/fixtures/asa_ogs_config.cfg, tests/unit/modules/network/asa/test_asa_ogs.py
Depends-on: https://github.com/ansible/ansible-zuul-jobs/pull/1463
To fix ASA Object groups where service and port object was running into exceptions. Fixes #152 and #153 
asa_ogs
```paste below
```
=> To fix ASA Object groups where service and port object was running into exceptions

CHANGELOG.rst, changelogs/changelog.yaml, changelogs/fragments/fix_for_the_ogs_bug_asa_152.yaml, changelogs/fragments/netcommon_ref_update.yaml, docs/cisco.asa.asa_cliconf.rst, docs/cisco.asa.asa_facts_module.rst, docs/cisco.asa.asa_ogs_module.rst
https://github.com/ansible-collections/splunk.es/pull/35
```paste below
```
=> Collection prep for 3.0.0 release

CHANGELOG.rst, changelogs/changelog.yaml, changelogs/fragments/github_actions.yaml, changelogs/fragments/remove_deprecated_modules.yaml, changelogs/fragments/remove_provider.yaml
PR for Cisco ASA 4.0.0 release prep
```paste below
```
=> PR for Cisco ASA 4.0.0 release prep

changelogs/fragments/rm_base.yaml, plugins/module_utils/network/asa/config/acls/acls.py, plugins/module_utils/network/asa/config/ogs/ogs.py, plugins/module_utils/network/asa/rm_templates/acls.py, plugins/module_utils/network/asa/rm_templates/ogs.py
The old name will be removed in netcommon 5.0.0
=> Redirect ResourceModule to new location

CHANGELOG.rst, changelogs/changelog.yaml, changelogs/fragments/cleanup.yaml, changelogs/fragments/pre-commit.yaml, changelogs/fragments/rm_base.yaml, changelogs/fragments/rm_base_plus.yaml, galaxy.yml
For the release prep of Cisco ASA collection with version 4.0.1
cisco.asa
```paste below
```
=> For the release prep of Cisco ASA collection with version 4.0.1

CHANGELOG.rst, changelogs/changelog.yaml, changelogs/fragments/bindep_fix.yaml, changelogs/fragments/test-net-2.yaml, galaxy.yml
=> Prepare release 4.0.2

changelogs/fragments/lint_fixtures.yaml, docs/cisco.asa.asa_acls_module.rst, docs/cisco.asa.asa_command_module.rst, docs/cisco.asa.asa_config_module.rst, docs/cisco.asa.asa_facts_module.rst, docs/cisco.asa.asa_ogs_module.rst, plugins/modules/asa_acls.py, plugins/modules/asa_command.py, plugins/modules/asa_config.py, plugins/modules/asa_facts.py, plugins/modules/asa_ogs.py
=> Ansible-lint error fixtures

CHANGELOG.rst, changelogs/changelog.yaml, changelogs/fragments/codecov_pr.yml, changelogs/fragments/lint_fixtures.yaml, galaxy.yml
=> Prepare release 4.0.3

CHANGELOG.rst, changelogs/changelog.yaml, changelogs/fragments/fix_module_defaults.yaml, galaxy.yml
=> Prepare Release 5.0.1

CHANGELOG.rst, changelogs/changelog.yaml, changelogs/fragments/add_2.18.yaml, changelogs/fragments/bump_215.yaml, galaxy.yml
=> Prepare release 6.0.0

changelogs/fragments/ignore_219.yaml, tests/sanity/ignore-2.19.txt
Fixes the upstream failing nightlies sanity error.
ignore-2.19.txt
```paste below
https://github.com/ansible-collections/cisco.asa/actions/runs/11023968434/job/30616295872#step:6:61
```
=> Adds ignore-2.19.txt
